### ISSUE TITLE
There's no .eleventy.js file

### ISSUE THREAD

**Issue by shanerobinson** [lcnichols/100daysofcode#1]
Hey @lcnichols - When working with 11ty, you should have an `.eleventy.js` file which provides config instructions to 11ty on how to work and where to look for files. 

Lots of helpful info on the 11ty Docs site: https://www.11ty.dev/docs/config/

**Comment by lcnichols** [comment]
@shanerobinson it wasn't super straight forward to me but after looking at the instructions for a bit, I created a blank file in my VS Code, then copy and pasted the top code in the instructions, not the API one (not sure what that was) and uploaded it to GitHub.

**Comment by shanerobinson** [comment]
So, in the new `.eleventy.js` file, you have `input: "views"` but the input dir should be `src` which already exists and contains all the 11ty templates and content files. 

_(SIDENOTE: This is one of the reasons I wanted to build a basic 11ty site with you from scratch instead of cloning or forking an existing repo. These very basic configs will be much easier to understand if you write them yourself -vs- trying to figure out what someone else did **WHILE** you're learning to code the basics of HTML. Plus... my repo has a LOT of extra dependencies that are old and not even needed any longer. It would be cleaner and easier to build from scratch rather than remodel.)_ 😉

**Comment by shanerobinson** [comment]
@lcnichols Since a `.eleventy.js` file now exists, it would be good practice to close this Issue. Any future Issues with config would be a separate Issue.

**Comment by lcnichols** [comment]
Ah, ok, we can still do that and use this for practice logging bugs or just ditch this. I'll keep my diary in Notes.App until we're there :-)
